### ISSUE TITLE
Cannot install package - Sublime Text 2.0.1

### ISSUE THREAD

**Issue by bmbrandx** [tomalec/Sublime-Text-2-Vlt-Plugin#1]
Receiving a decoding error on installation of package through Sublime's Console.

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./Package Control.py", line 1871, in run
  File "./Package Control.py", line 1465, in install_package
  File "./Package Control.py", line 1533, in print_messages
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 397: ordinal not in range(128)

**Comment by tomalec** [comment]
Thanks for feedback,
I've submitted bdecab9, try this time.
